### ISSUE TITLE
[Feat] User login and register

### ISSUE THREAD

**Issue by asas1asas200** [asas1asas200/NTOUClassroomBorrowing#32]
- [ ] Register
- [ ] Login

Permission Control

**Comment by Argentum11** [comment]
@asas1asas200 
What does Permission Control mean in this issue? Do I have to block something from the user?

**Comment by asas1asas200** [comment]
If a regular user want to visit admin page, return a 403 status code.

**Comment by asas1asas200** [comment]
But this work need to finish the DB first.
